version: "3.8"

x-base: &base
    image: protector_backend
    volumes:
        - .:/project/app:cached
        - static:/project/static
        - media:/project/media
    depends_on:
        - postgres
    env_file: .env
    restart: "on-failure"

services:
    postgres:
        image: postgres:13.3-alpine
        environment:
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - pg-data:/var/lib/postgresql/data:delegated
        ports:
            - "5432:5432"

    django:
        <<: *base
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        command: python src/manage.py runserver 0:8000
        ports:
            - "8000:8000"

    bootstrapper:
        <<: *base
        command: python src/manage.py bootstrap

volumes:
    pg-data: {}
    static: {}
    media: {}
