version: "3.8"

# x-base: &datatap-base
#     image: datatap_backend
#     volumes:
#         - ../datatap/:/app/datatap/:cached
#         - ../conf/:/app/conf/:cached
#         - datatap-storage-data:/var/lib/datatap:delegated
#         - datatap-storage-logs:/var/log/datatap:delegated
#     depends_on:
#         - postgres
#         - redis
#     env_file: ./.env
#     restart: "on-failure"
#     networks:
#         - default

services:
    postgres:
        image: postgres:13.3-alpine
        env_file: ./docker/.postgres.env
        volumes:
            - protector-postgresql-data:/var/lib/postgresql/data:delegated
        ports:
            - "5432:5432"

volumes:
    protector-postgresql-data: {}
